Featured branch
Buyaki01/background-and-gradients pull request #2
Opened 2020-02-08 13:16 UTC by Buyaki01

This project entails cloning the old apple homepage. I had initially created a pull request of the same project but with a different repo-name: apple-clone. I decided to create a new repository because my previous repository had some issues which could not be resolved. I used the main tag to hold the contents of the navigation bar and the contents just below the navigation bar. In the main tag, i used different tags such as: the header, nav, div, fieldset, ul, li, a, form, input, i, section, h2, h3, span tags to achieve it's purpose. I also used the aside tag to hold the iphone images in the old apple homepage. To achieve this, i used the ul, li, a, img tags inside the aside tag. Finally, I used the footer tag to hold the contents of the footer in the old apple homepage. Inside the footer tag, i used the following tags: div, ul, li, p, a, span, img tags. Created a folder called css to hold my style.css file which has the code i used to style the index.html file. I also included a copy of  .stickler.yml  and stylelint.config.js files in my repository. I also updated my README file in my repository, it gives a brief explanation on what my project entails.

2020-02-08 14:24 UTC, mosesogwo requested changes
### Hi @Buyaki01, nice work :+1:. We need to fix the following:

1. Your page has a horizontal scroll. Its coming from the sizing in/of your footer section. Kindly fix this.

2. I have left some comments on your html and css files. Take care of them.

_**Kindly make these changes and submit another code review request.**_

**Cheers:smile:**

2020-02-08 14:24 UTC, mosesogwo commented on css/style.css
> +}
Merge these into one.

2020-02-08 14:24 UTC, mosesogwo commented on css/style.css
> +}
Merge into one.

2020-02-08 14:24 UTC, mosesogwo commented on css/style.css
> +}
Merge into one style

2020-02-08 14:24 UTC, mosesogwo commented on css/style.css
> +}
Merge into one style. You can also combine these with the style in lines 110 - 116 since its the same single style for all of them.

2020-02-08 14:24 UTC, mosesogwo commented on css/style.css
> +}
Merge.

2020-02-08 14:24 UTC, mosesogwo commented on index.html
> +                <li><a href="#"><span style="text-align: end;"> Media Info </span>|</a></li>
Remove inline style

2020-02-09 04:31 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Buyaki01 :wave: 

### Thank you for doing the changes required by the previous reviewer :medal_sports: the gradient in your navbar looks really close to the original :microscope: and you have used Semantic HTML as it should be :clap: :clap: 

### There are still some changes to make as you can see next :point_down: 

## Navbar

- [ ] Please align the labels of each button a little more especially the apple icon as it seems to be aligned to the left when it should be aligned in the center/middle of the button

- Yours

![image](https://user-images.githubusercontent.com/52209067/74096111-fd791000-4abf-11ea-8462-0d7d3569ffb1.png)

- Original

![image](https://user-images.githubusercontent.com/52209067/74096122-20a3bf80-4ac0-11ea-87c9-135209290983.png)

## Content position

- [ ] The whole content of your page seems to be aligned to the left, when it should be centered and also take 100% of the screen width. let's fix it!

![image](https://user-images.githubusercontent.com/52209067/74096171-d4a54a80-4ac0-11ea-8856-c8a78a44da29.png)

## Building with backgrounds

[OPTIONAL] this project is all about building with backgrounds and gradients, so I deeply eager you to change all the `<img> `tags in your aside section to be `<div>` tags with background images

### That's it! :raised_hands: 

### Please :pray:  do the changes :memo:  and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any question? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-10 12:27 UTC, fatymahmed approved these changes
## Hi @Buyaki01,
### Great job making all the suggested changes🎉🎉
### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
 _Don't forget to submit your project completion form_

2020-02-10 12:58 UTC, merged